// EdgeOne Functions - Auto-generated from generate-source.js
// DO NOT EDIT THIS FILE DIRECTLY


// shared/prompt/dimensions.js
var styleDimensions = {
  "\u66A7\u6627": [
    "\u521D\u6B21\u89C1\u9762\u7684\u5370\u8C61",
    "\u8EAB\u4F53\u63A5\u89E6\u7684\u5C34\u5C2C\u77AC\u95F4",
    "\u6697\u604B\u7684\u79D8\u5BC6",
    "\u7EA6\u4F1A\u4E2D\u7684\u5C0F\u7EC6\u8282",
    "\u66A7\u6627\u7684\u80A2\u4F53\u8BED\u8A00",
    "\u6027\u5438\u5F15\u529B",
    "\u6D6A\u6F2B\u5E7B\u60F3",
    "\u4EB2\u5BC6\u5173\u7CFB\u8FB9\u754C",
    "\u4E2A\u4EBA\u559C\u597D"
  ],
  "\u641E\u7B11": [
    "\u5C34\u5C2C\u7CD7\u4E8B",
    "\u7AE5\u5E74\u8DA3\u4E8B",
    "\u6A21\u4EFF\u8868\u6F14",
    "\u5947\u8469\u7ECF\u5386",
    "\u793E\u6B7B\u77AC\u95F4",
    "\u6076\u641E\u6311\u6218",
    "\u8352\u8BDE\u60F3\u8C61",
    "\u6C99\u96D5\u884C\u4E3A",
    "\u4E2A\u4EBA\u559C\u597D"
  ],
  "\u793E\u725B": [
    "\u5927\u80C6\u642D\u8BAA",
    "\u516C\u5F00\u8868\u6F14",
    "\u793E\u4EA4\u6311\u6218",
    "\u5373\u5174\u6F14\u8BB2",
    "\u964C\u751F\u4EBA\u4E92\u52A8",
    "\u81EA\u6211\u5C55\u793A",
    "\u7834\u51B0\u6E38\u620F",
    "\u52C7\u6562\u8868\u8FBE",
    "\u4E2A\u4EBA\u559C\u597D"
  ],
  "\u804C\u573A": [
    "\u804C\u573A\u653F\u6CBB",
    "\u9886\u5BFC\u5173\u7CFB",
    "\u540C\u4E8B\u516B\u5366",
    "\u804C\u4E1A\u89C4\u5212",
    "\u5DE5\u4F5C\u5931\u8BEF",
    "\u529E\u516C\u5BA4\u604B\u60C5",
    "\u8DF3\u69FD\u7ECF\u5386",
    "\u804C\u573A\u56F0\u5883",
    "\u4E2A\u4EBA\u559C\u597D"
  ],
  "\u9152\u5C40": [
    "\u9152\u91CF\u7CD7\u4E8B",
    "\u9152\u540E\u5931\u6001",
    "\u529D\u9152\u6587\u5316",
    "\u559D\u9152\u6E38\u620F",
    "\u9152\u684C\u89C4\u77E9",
    "\u9189\u9152\u7ECF\u5386",
    "\u62FC\u9152\u6311\u6218",
    "\u9152\u540E\u771F\u8BDD",
    "\u4E2A\u4EBA\u559C\u597D"
  ],
  "\u5BB6\u5EAD": [
    "\u7236\u6BCD\u5173\u7CFB",
    "\u5144\u5F1F\u59D0\u59B9",
    "\u5BB6\u5EAD\u79D8\u5BC6",
    "\u7AE5\u5E74\u56DE\u5FC6",
    "\u5BB6\u65CF\u4F20\u7EDF",
    "\u4EE3\u9645\u51B2\u7A81",
    "\u4EB2\u60C5\u65F6\u523B",
    "\u5BB6\u5EAD\u8D23\u4EFB",
    "\u4E2A\u4EBA\u559C\u597D"
  ],
  "\u70E7\u8111": [
    "\u903B\u8F91\u63A8\u7406",
    "\u9053\u5FB7\u56F0\u5883",
    "\u54F2\u5B66\u601D\u8003",
    "\u5047\u8BBE\u60C5\u5883",
    "\u4EF7\u503C\u9009\u62E9",
    "\u5FC3\u7406\u6D4B\u8BD5",
    "\u667A\u529B\u6311\u6218",
    "\u6DF1\u5EA6\u8FFD\u95EE",
    "\u4E2A\u4EBA\u559C\u597D"
  ],
  "\u6781\u9650": [
    "\u6050\u9AD8\u6311\u6218",
    "\u793E\u4EA4\u6050\u60E7",
    "\u8EAB\u4F53\u6781\u9650",
    "\u5FC3\u7406\u538B\u529B",
    "\u5192\u9669\u7ECF\u5386",
    "\u751F\u5B58\u8003\u9A8C",
    "\u52C7\u6C14\u6D4B\u8BD5",
    "\u7A81\u7834\u8212\u9002\u533A",
    "\u4E2A\u4EBA\u559C\u597D"
  ],
  "\u6D3E\u5BF9": [
    "\u6E38\u620F\u4E92\u52A8",
    "\u624D\u827A\u8868\u6F14",
    "\u56E2\u961F\u534F\u4F5C",
    "\u5373\u5174\u521B\u4F5C",
    "\u8282\u594F\u6311\u6218",
    "\u89D2\u8272\u626E\u6F14",
    "\u96C6\u4F53\u60E9\u7F5A",
    "\u70ED\u573A\u6D3B\u52A8",
    "\u4E2A\u4EBA\u559C\u597D"
  ],
  "\u6E29\u60C5": [
    "\u611F\u6069\u65F6\u523B",
    "\u53CB\u60C5\u56DE\u5FC6",
    "\u5584\u826F\u884C\u4E3A",
    "\u6E29\u6696\u77AC\u95F4",
    "\u5FC3\u7075\u6210\u957F",
    "\u771F\u8BDA\u8868\u8FBE",
    "\u60C5\u611F\u652F\u6301",
    "\u7F8E\u597D\u613F\u671B",
    "\u4E2A\u4EBA\u559C\u597D"
  ],
  "\u5927\u5C3A\u5EA6": [
    "\u6027\u7ECF\u5386",
    "\u8EAB\u4F53\u9690\u79C1",
    "\u6027\u5E7B\u60F3",
    "\u60C5\u6B32\u6311\u6218",
    "\u4EB2\u5BC6\u63A5\u89E6",
    "\u6027\u8BDD\u9898",
    "\u5927\u80C6\u8868\u767D",
    "\u7981\u5FCC\u8FB9\u7F18",
    "\u4E2A\u4EBA\u559C\u597D"
  ],
  "\u5C11\u513F\u9002\u5B9C": [
    "\u6821\u56ED\u8DA3\u4E8B",
    "\u5174\u8DA3\u7231\u597D",
    "\u52A8\u753B\u6E38\u620F",
    "\u8FD0\u52A8\u6311\u6218",
    "\u624D\u827A\u5C55\u793A",
    "\u53CB\u8C0A\u6545\u4E8B",
    "\u68A6\u60F3\u5206\u4EAB",
    "\u521B\u610F\u60F3\u8C61",
    "\u4E2A\u4EBA\u559C\u597D"
  ],
  "\u6B63\u5E38": [
    "\u751F\u6D3B\u7ECF\u5386",
    "\u4EBA\u9645\u5173\u7CFB",
    "\u4E2A\u4EBA\u6210\u957F",
    "\u5174\u8DA3\u7231\u597D",
    "\u672A\u6765\u89C4\u5212",
    "\u4EF7\u503C\u89C2\u5FF5",
    "\u60C5\u611F\u8868\u8FBE",
    "\u793E\u4EA4\u4E92\u52A8",
    "\u4E2A\u4EBA\u559C\u597D"
  ]
};
function getDimensionHint(style) {
  const dimensions = styleDimensions[style] || [];
  if (dimensions.length === 0) {
    return "";
  }
  return `
\u8BDD\u9898\u7EF4\u5EA6\u53C2\u8003\uFF08\u8BF7\u4ECE\u4E2D\u9009\u62E9\u4E0D\u540C\u7EF4\u5EA6\uFF0C\u907F\u514D\u91CD\u590D\uFF09\uFF1A${dimensions.join("\u3001")}`;
}

// shared/prompt/builder.js
function buildPrompt({ mode, style, locale, count, audienceAge, intensity, seed }) {
  const isExplicit = style === "\u5927\u5C3A\u5EA6";
  const dimensions = styleDimensions[style] || styleDimensions["\u6B63\u5E38"] || [];
  if (dimensions.length === 0) {
    console.warn(`[Prompt] \u672A\u627E\u5230\u98CE\u683C "${style}" \u7684\u7EF4\u5EA6\u5B9A\u4E49\uFF0C\u4F7F\u7528\u7A7A\u7EF4\u5EA6`);
  }
  const targetDimensionIndex = dimensions.length > 0 ? Math.floor(Math.random() * dimensions.length) : null;
  const targetDimension = targetDimensionIndex !== null ? dimensions[targetDimensionIndex] : null;
  const dimensionHint = getDimensionHint(style);
  let systemPrompt;
  const modeInstruction = mode === "truth" ? `
**\u771F\u5FC3\u8BDD\uFF08Truth\uFF09\u6A21\u5F0F - \u4E25\u683C\u8981\u6C42**\uFF1A
\u2705 \u5FC5\u987B\u662F\uFF1A
  - \u63D0\u95EE\u3001\u8BE2\u95EE\u3001\u8981\u6C42\u56DE\u7B54
  - \u8BA9\u73A9\u5BB6\u7528\u8BED\u8A00\u8868\u8FBE\uFF1A\u8BB2\u8FF0\u3001\u63CF\u8FF0\u3001\u56DE\u7B54\u3001\u5206\u4EAB
  - \u9898\u76EE\u5F00\u5934\uFF1A\u4F60..., \u63CF\u8FF0..., \u8BB2\u8FF0..., \u8BF4\u8BF4..., \u56DE\u5FC6...
  
\u274C \u7EDD\u5BF9\u7981\u6B62\uFF1A
  - \u4EFB\u4F55\u9700\u8981"\u505A\u52A8\u4F5C"\u7684\u5185\u5BB9\uFF08\u5982\uFF1A\u6A21\u4EFF\u3001\u8868\u6F14\u3001\u505A\u51FA...\u52A8\u4F5C\uFF09
  - \u4EFB\u4F55\u9700\u8981"\u6267\u884C\u4EFB\u52A1"\u7684\u5185\u5BB9\uFF08\u5982\uFF1A\u5B8C\u6210\u3001\u6311\u6218\uFF09
  - \u9898\u76EE\u4E2D\u4E0D\u80FD\u51FA\u73B0\uFF1A\u6A21\u4EFF\u3001\u8868\u6F14\u3001\u505A\u3001\u6267\u884C\u3001\u5B8C\u6210\u3001\u52A8\u4F5C\u3001\u59FF\u52BF\u7B49\u52A8\u8BCD
  
\u793A\u4F8B\uFF08\u6B63\u786E\uFF09\uFF1A
  - \u4F60\u6700\u5C34\u5C2C\u7684\u4E00\u6B21\u7ECF\u5386\u662F\u4EC0\u4E48\uFF1F
  - \u63CF\u8FF0\u4F60\u7AE5\u5E74\u65F6\u6700\u6709\u8DA3\u7684\u4E00\u6B21\u6076\u4F5C\u5267
  - \u8BB2\u8FF0\u4F60\u4EBA\u751F\u4E2D\u6700'\u793E\u6B7B'\u7684\u77AC\u95F4` : `
**\u5927\u5192\u9669\uFF08Dare\uFF09\u6A21\u5F0F - \u4E25\u683C\u8981\u6C42**\uFF1A
\u2705 \u5FC5\u987B\u662F\uFF1A
  - \u547D\u4EE4\u3001\u6307\u4EE4\u3001\u8981\u6C42\u6267\u884C
  - \u8BA9\u73A9\u5BB6\u73B0\u573A\u505A\u52A8\u4F5C\uFF1A\u6A21\u4EFF\u3001\u8868\u6F14\u3001\u505A\u51FA\u3001\u5B8C\u6210
  - \u9898\u76EE\u5F00\u5934\uFF1A\u6A21\u4EFF..., \u505A\u51FA..., \u8868\u6F14..., \u5B8C\u6210..., \u5411...\u505A...
  
\u274C \u7EDD\u5BF9\u7981\u6B62\uFF1A
  - \u4EFB\u4F55\u53EA\u9700\u8981"\u8BF4\u8BDD\u56DE\u7B54"\u7684\u5185\u5BB9
  - \u9898\u76EE\u4E2D\u4E0D\u80FD\u53EA\u662F\uFF1A\u8BB2\u8FF0\u3001\u63CF\u8FF0\u3001\u56DE\u7B54\u3001\u8BF4\u8BF4\u3001\u56DE\u5FC6\u7B49\u7EAF\u8BED\u8A00\u8868\u8FBE
  
\u793A\u4F8B\uFF08\u6B63\u786E\uFF09\uFF1A
  - \u6A21\u4EFF\u4E00\u79CD\u52A8\u7269\u53EB\u58F0\u6301\u7EED10\u79D2
  - \u7528\u6700\u5938\u5F20\u7684\u59FF\u52BF\u5B8C\u62105\u4E2A\u6DF1\u8E72
  - \u5BF9\u7740\u623F\u95F4\u91CC\u7684\u4E00\u4E2A\u7269\u54C1\u8868\u767D30\u79D2`;
  if (isExplicit) {
    systemPrompt = `
\u4F60\u662F\u6210\u4EBA\u6D3E\u5BF9\u4E92\u52A8\u7B56\u5212\u52A9\u624B\u3002\u6839\u636E\u6A21\u5F0F\u751F\u6210\u5927\u80C6\u3001\u523A\u6FC0\u7684\u95EE\u9898\u6216\u4EFB\u52A1\uFF0C\u9002\u540818\u5C81\u4EE5\u4E0A\u6210\u4EBA\u805A\u4F1A\u3002
\u53EF\u4EE5\u4F46\u4E0D\u9650\u4E8E\u5305\u542B\uFF1A\u66A7\u6627\u8BDD\u9898\u3001\u6027\u6697\u793A\u3001\u8F7B\u5EA6\u8EAB\u4F53\u63A5\u89E6\u6311\u6218\u3001\u996E\u9152\u60E9\u7F5A\u3001\u6076\u4F5C\u5267\u6311\u6218\u3001\u9690\u79C1\u8EAB\u4F53\u90E8\u4F4D\u3001\u6027\u7ECF\u5386\u7B49\u3002
\u7981\u6B62\u5305\u542B\uFF1A\u8FDD\u6CD5\u5185\u5BB9\u3001\u6D89\u53CA\u672A\u6210\u5E74\u4EBA\u3001\u6B67\u89C6\u6027\u5185\u5BB9\u3001\u4E25\u91CD\u66B4\u529B\u3002
\u751F\u6210\u9898\u76EE\u7684\u573A\u666F\u548C\u8BDD\u9898\u8981\u591A\u53D8\uFF0C\u907F\u514D\u5355\u4E00\u91CD\u590D\uFF0C\u52AA\u529B\u8BA9\u6D3E\u5BF9\u6301\u7EED\u5347\u6E29\u548C\u6709\u8DA3\u3002
\u786E\u4FDD\u8BED\u8A00\u7B80\u6D01\uFF0C\u4EFB\u52A1\u53EF\u6267\u884C\u3002

\u26A0\uFE0F \u91CD\u8981\u683C\u5F0F\u8981\u6C42\uFF1A
- \u9898\u76EE\u5185\u5BB9\u4E2D\u4E0D\u8981\u4F7F\u7528\u53CC\u5F15\u53F7(")\uFF0C\u53EF\u4EE5\u7528\u5355\u5F15\u53F7(')\u3001\u4E66\u540D\u53F7(\u300A\u300B)\u6216\u76F4\u63A5\u7701\u7565\u5F15\u53F7
- \u907F\u514D\u4F7F\u7528\u53EF\u80FD\u7834\u574F JSON \u683C\u5F0F\u7684\u7279\u6B8A\u5B57\u7B26

${modeInstruction}

\u8F93\u51FA\u683C\u5F0F\u4E3A\u4E25\u683C\u7684 JSON \u6570\u7EC4\uFF0C\u6BCF\u9879\u5305\u542B type\uFF08${mode}\uFF09\u4E0E text\uFF08\u9898\u76EE\u5185\u5BB9\uFF09\u3002
\u26A0\uFE0F \u7279\u522B\u6CE8\u610F\uFF1Atext \u5B57\u6BB5\u7684\u5185\u5BB9\u4E2D\u4E0D\u80FD\u51FA\u73B0\u53CC\u5F15\u53F7(")\uFF0C\u5426\u5219\u4F1A\u5BFC\u81F4 JSON \u89E3\u6790\u5931\u8D25\u3002

\u793A\u4F8B\uFF1A
[
  {"type": "${mode}", "text": "${mode === "truth" ? "\u4F60\u6700\u5927\u80C6\u7684\u4E00\u6B21\u7EA6\u4F1A\u7ECF\u5386\u662F\u4EC0\u4E48\uFF1F" : "\u9009\u4E00\u4E2A\u4EBA\uFF0C\u7528\u773C\u795E\u5BF9\u89C630\u79D2\u4E0D\u8BB8\u7B11"}"}
]
`;
  } else {
    systemPrompt = `
\u4F60\u662F\u6D3E\u5BF9\u4E92\u52A8\u7B56\u5212\u52A9\u624B\u3002\u6839\u636E\u6A21\u5F0F\u4E0E\u98CE\u683C\u751F\u6210\u7B80\u6D01\u3001\u53EF\u6267\u884C\u7684\u95EE\u9898\u6216\u4EFB\u52A1\uFF0C\u907F\u514D\u4E0D\u5F53\u5185\u5BB9\u3002
\u751F\u6210\u9898\u76EE\u7684\u573A\u666F\u548C\u8BDD\u9898\u8981\u591A\u53D8\uFF0C\u907F\u514D\u5355\u4E00\u91CD\u590D\uFF0C\u52AA\u529B\u8BA9\u6D3E\u5BF9\u6301\u7EED\u5347\u6E29\u548C\u6709\u8DA3\u3002

${modeInstruction}

\u8F93\u51FA\u683C\u5F0F\u4E3A\u4E25\u683C\u7684 JSON \u6570\u7EC4\uFF0C\u6BCF\u9879\u5305\u542B type\uFF08${mode}\uFF09\u4E0E text\uFF08\u9898\u76EE\u5185\u5BB9\uFF09\u3002
\u793A\u4F8B\uFF1A
[
  {"type": "${mode}", "text": "${mode === "truth" ? "\u4F60\u6700\u5C34\u5C2C\u7684\u4E00\u6B21\u7ECF\u5386\u662F\u4EC0\u4E48\uFF1F" : "\u6A21\u4EFF\u4E00\u79CD\u52A8\u7269\u53EB\u58F0\u6301\u7EED10\u79D2"}"}
]
`;
  }
  let userPrompt = `
\u8BED\u8A00\uFF1A${locale}\uFF1B\u6A21\u5F0F\uFF1A${mode}\uFF1B\u98CE\u683C\uFF1A${style}\uFF1B\u6570\u91CF\uFF1A${count}
\u53D7\u4F17\u5E74\u9F84\uFF1A${audienceAge}\uFF1B\u5C3A\u5EA6\uFF1A${intensity}\uFF1B\u9898\u76EE\u7F16\u53F7\uFF1A${seed || "N/A"}`;
  if (targetDimension) {
    userPrompt += `

\u{1F3AF} \u672C\u6B21\u6838\u5FC3\u8BDD\u9898\u7EF4\u5EA6\uFF1A\u3010${targetDimension}\u3011
\u26A0\uFE0F \u8BF7\u4E25\u683C\u56F4\u7ED5"${targetDimension}"\u8FD9\u4E2A\u7EF4\u5EA6\u8BBE\u8BA1\u9898\u76EE\u5185\u5BB9\uFF0C\u4E0D\u8981\u504F\u79BB\u5230\u5176\u4ED6\u7EF4\u5EA6\u3002
\u5982\u679C\u7EF4\u5EA6\u662F"\u7AE5\u5E74\u8DA3\u4E8B"\uFF0C\u5C31\u4E0D\u8981\u8BBE\u8BA1\u6210"\u6A21\u4EFF\u8868\u6F14"\uFF1B
\u5982\u679C\u7EF4\u5EA6\u662F"\u5C34\u5C2C\u7CD7\u4E8B"\uFF0C\u5C31\u8BBE\u8BA1\u56DE\u5FC6\u5C34\u5C2C\u7ECF\u5386\u7684\u95EE\u9898\u6216\u4EFB\u52A1\uFF0C\u800C\u4E0D\u662F\u8868\u6F14\u7C7B\u3002
\u6BCF\u4E2A\u7EF4\u5EA6\u90FD\u6709\u72EC\u7279\u7684\u8868\u8FBE\u65B9\u5F0F\uFF0C\u8BF7\u5145\u5206\u53D1\u6325\u521B\u610F\u3002`;
  } else if (dimensionHint) {
    userPrompt += dimensionHint;
  }
  userPrompt += `

\u8BF7\u751F\u6210 ${count} \u6761\u7B26\u5408\u8981\u6C42\u7684\u5185\u5BB9\uFF0C\u4E25\u683C\u9075\u5B88 JSON \u683C\u5F0F\u3002`;
  return {
    system: systemPrompt.trim(),
    user: userPrompt.trim()
  };
}

// shared/config/llm-params.js
var llmParams = {
  // 🎲 采样参数
  temperature: 1,
  // 随机性（0-2，越高越随机）
  maxTokens: 1e3,
  // 最大生成 token 数
  frequencyPenalty: 1.5,
  // 重复词惩罚（-2 到 2，正值减少重复）
  presencePenalty: 1.2,
  // 话题惩罚（-2 到 2，正值鼓励新话题）
  // 🤖 模型配置
  models: {
    tongyi: "qwen-plus",
    // 可选: qwen-max, qwen-turbo
    deepseek: "deepseek-chat"
  },
  // 💾 缓存配置
  cache: {
    ttl: 600,
    // TTL（秒）- 10 分钟
    maxSize: 100
    // 最大缓存条数（LRU）
  },
  // 🚦 限流配置
  rateLimit: {
    perMinute: 20
    // 每分钟最大请求次数
  }
};

// functions/api/generate-source.js
var SENSITIVE_WORDS = [
  // 违法相关（保留）
  "\u6BD2\u54C1",
  "\u8BC8\u9A97",
  "\u8D4C\u535A",
  "\u8D70\u79C1",
  "\u8D29\u5356",
  // 严重暴力（保留）
  "\u6740\u4EBA",
  "\u780D\u6740",
  "\u8650\u5F85",
  "\u7ED1\u67B6",
  // 未成年保护（保留）
  "\u672A\u6210\u5E74",
  "\u513F\u7AE5\u8272\u60C5",
  "\u604B\u7AE5",
  // 歧视相关（保留）
  "\u6B67\u89C6",
  "\u79CD\u65CF\u6B67\u89C6",
  "\u5730\u57DF\u9ED1",
  "\u6027\u522B\u6B67\u89C6",
  "\u6B8B\u75BE\u6B67\u89C6",
  // 极端内容（保留）
  "\u81EA\u6740",
  "\u81EA\u6B8B",
  "\u90AA\u6559",
  "\u6050\u6016\u4E3B\u4E49"
];
var SENSITIVE_WORDS_EXPLICIT = [
  // 违法相关（保留）
  "\u6BD2\u54C1",
  "\u8BC8\u9A97",
  "\u8D4C\u535A",
  "\u8D70\u79C1",
  "\u8D29\u5356",
  // 严重暴力（保留）
  "\u6740\u4EBA",
  "\u780D\u6740",
  "\u8650\u5F85",
  "\u7ED1\u67B6",
  // 未成年保护（保留）
  "\u672A\u6210\u5E74",
  "\u513F\u7AE5\u8272\u60C5",
  "\u604B\u7AE5",
  // 歧视相关（保留）
  "\u6B67\u89C6",
  "\u79CD\u65CF\u6B67\u89C6",
  "\u5730\u57DF\u9ED1",
  "\u6027\u522B\u6B67\u89C6",
  "\u6B8B\u75BE\u6B67\u89C6",
  // 极端内容（保留）
  "\u81EA\u6740",
  "\u81EA\u6B8B",
  "\u90AA\u6559",
  "\u6050\u6016\u4E3B\u4E49"
];
function containsSensitive(text, isExplicit = false) {
  const words = isExplicit ? SENSITIVE_WORDS_EXPLICIT : SENSITIVE_WORDS;
  const lowerText = text.toLowerCase();
  return words.some((word) => lowerText.includes(word.toLowerCase()));
}
function filterItems(items, isExplicit = false) {
  return items.filter((item) => !containsSensitive(item.text, isExplicit));
}
function parseResponse(rawText) {
  try {
    let jsonString = rawText.trim();
    jsonString = jsonString.replace(/```json\s*/gi, "").replace(/```\s*/g, "");
    jsonString = jsonString.replace(/^\s*\{\s*\[/, "[").replace(/\]\s*\}\s*$/, "]");
    const jsonMatch = jsonString.match(/\[([\s\S]*)\]/);
    if (jsonMatch) {
      jsonString = `[${jsonMatch[1]}]`;
    }
    try {
      const items = JSON.parse(jsonString);
      if (Array.isArray(items) && items.length > 0 && items[0].text) {
        return items.map((item, index) => ({
          id: `gen-${Date.now()}-${index}`,
          type: item.type,
          text: item.text
        }));
      }
    } catch (parseError) {
      console.warn("[LLM] JSON\u89E3\u6790\u5931\u8D25\uFF0C\u5C1D\u8BD5\u624B\u52A8\u63D0\u53D6:", parseError.message);
    }
    const typeMatch = jsonString.match(/[""]type[""]\s*:\s*[""]?(truth|dare)[""]?/i);
    if (!typeMatch) {
      throw new Error("\u65E0\u6CD5\u63D0\u53D6 type \u5B57\u6BB5");
    }
    const textFieldMatch = jsonString.match(/[""]text[""]\s*:\s*[""]/);
    if (!textFieldMatch) {
      throw new Error("\u65E0\u6CD5\u63D0\u53D6 text \u5B57\u6BB5");
    }
    const textValueStart = jsonString.indexOf(textFieldMatch[0]) + textFieldMatch[0].length;
    let textContent = jsonString.substring(textValueStart);
    textContent = textContent.replace(/[""]\s*\}[\s\}\]]*$/, "");
    textContent = textContent.replace(/\\n/g, "\n").replace(/\\"/g, '"').replace(/\\\\/g, "\\");
    console.log("[LLM] \u624B\u52A8\u63D0\u53D6\u6210\u529F");
    return [{
      id: `gen-${Date.now()}-0`,
      type: typeMatch[1],
      text: textContent
    }];
  } catch (err) {
    console.error("[LLM] \u89E3\u6790\u54CD\u5E94\u5931\u8D25:", rawText.substring(0, 300), "...\u9519\u8BEF:", err.message);
    const preview = rawText.substring(0, 100).replace(/[\n\r]/g, "\\n");
    throw new Error(`LLM\u54CD\u5E94\u89E3\u6790\u5931\u8D25: ${err.message} [\u539F\u59CB\u54CD\u5E94: ${preview}...]`);
  }
}
async function callLLM(env, { mode, style, locale, count, audienceAge, intensity, seed }) {
  const provider = env.LLM_PROVIDER || "deepseek";
  const prompt = buildPrompt({ mode, style, locale, count, audienceAge, intensity, seed });
  let apiUrl, apiKey, model;
  if (provider === "tongyi") {
    apiUrl = "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions";
    apiKey = env.TONGYI_API_KEY;
    model = llmParams.models.tongyi;
  } else if (provider === "deepseek") {
    apiUrl = "https://api.deepseek.com/v1/chat/completions";
    apiKey = env.DEEPSEEK_API_KEY;
    model = llmParams.models.deepseek;
  } else {
    throw new Error(`\u4E0D\u652F\u6301\u7684 LLM \u4F9B\u5E94\u5546: ${provider}`);
  }
  if (!apiKey) {
    throw new Error(`\u672A\u914D\u7F6E ${provider.toUpperCase()}_API_KEY \u73AF\u5883\u53D8\u91CF`);
  }
  const response = await fetch(apiUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: prompt.system },
        { role: "user", content: prompt.user }
      ],
      temperature: llmParams.temperature,
      max_tokens: llmParams.maxTokens,
      frequency_penalty: llmParams.frequencyPenalty,
      presence_penalty: llmParams.presencePenalty
    })
  });
  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`LLM API \u8C03\u7528\u5931\u8D25: ${response.status} ${errorText}`);
  }
  const data = await response.json();
  const rawText = data.choices?.[0]?.message?.content?.trim() || "";
  return parseResponse(rawText);
}
var cache = /* @__PURE__ */ new Map();
function getCacheKey({ mode, style, seed }) {
  return `${mode}:${style}:${seed}`;
}
function getFromCache(key) {
  const entry = cache.get(key);
  if (entry && Date.now() - entry.timestamp < llmParams.cache.ttl * 1e3) {
    return entry.data;
  }
  cache.delete(key);
  return null;
}
function setToCache(key, data) {
  if (cache.size >= llmParams.cache.maxSize) {
    const firstKey = cache.keys().next().value;
    cache.delete(firstKey);
  }
  cache.set(key, { data, timestamp: Date.now() });
}
var rateLimitStore = /* @__PURE__ */ new Map();
function checkRateLimit(clientIp) {
  const now = Date.now();
  if (!rateLimitStore.has(clientIp)) {
    rateLimitStore.set(clientIp, []);
  }
  const requests = rateLimitStore.get(clientIp);
  const windowStart = now - 60 * 1e3;
  rateLimitStore.set(clientIp, requests.filter((ts) => ts > windowStart));
  if (rateLimitStore.get(clientIp).length >= llmParams.rateLimit.perMinute) {
    return false;
  }
  rateLimitStore.get(clientIp).push(now);
  return true;
}
function jsonResponse(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type"
    }
  });
}
async function onRequest(context) {
  const { request, env } = context;
  const startTime = Date.now();
  if (request.method === "OPTIONS") {
    return jsonResponse({}, 204);
  }
  if (request.method !== "POST") {
    return jsonResponse({ error: "\u4EC5\u652F\u6301 POST \u8BF7\u6C42" }, 405);
  }
  const clientIp = request.headers.get("CF-Connecting-IP") || "unknown";
  if (!checkRateLimit(clientIp)) {
    return jsonResponse({
      error: `\u8BF7\u6C42\u8FC7\u4E8E\u9891\u7E41\uFF0C\u8BF7\u7A0D\u540E\u518D\u8BD5\uFF08\u9650\u5236\uFF1A${llmParams.rateLimit.perMinute} \u6B21/\u5206\u949F\uFF09`
    }, 429);
  }
  try {
    const body = await request.json();
    const {
      mode,
      style,
      locale = "zh-CN",
      count = 1,
      audienceAge = "adult",
      intensity: reqIntensity = "medium",
      seed
    } = body;
    if (!mode || !["truth", "dare"].includes(mode)) {
      return jsonResponse({ error: "mode \u53C2\u6570\u65E0\u6548\uFF0C\u5FC5\u987B\u662F truth \u6216 dare" }, 400);
    }
    if (!style) {
      return jsonResponse({ error: "\u7F3A\u5C11 style \u53C2\u6570" }, 400);
    }
    if (count < 1 || count > 20) {
      return jsonResponse({ error: "count \u53C2\u6570\u8303\u56F4\u4E3A 1-20" }, 400);
    }
    let intensity = reqIntensity;
    if (style === "\u5927\u5C3A\u5EA6") {
      intensity = "hard";
    }
    const cacheParams = { mode, style, locale, audienceAge, intensity, count, seed };
    const cacheKey = getCacheKey(cacheParams);
    const cachedResult = getFromCache(cacheKey);
    if (cachedResult) {
      return jsonResponse({
        ...cachedResult,
        meta: {
          ...cachedResult.meta,
          cached: true,
          latencyMs: Date.now() - startTime,
          seed
        }
      });
    }
    const rawItems = await callLLM(env, { mode, style, locale, count, audienceAge, intensity, seed });
    const isExplicit = style === "\u5927\u5C3A\u5EA6";
    const filteredItems = filterItems(rawItems, isExplicit);
    const filteredCount = rawItems.length - filteredItems.length;
    const result = {
      items: filteredItems,
      meta: {
        provider: env.LLM_PROVIDER || "deepseek",
        promptId: "prompt-002",
        latencyMs: Date.now() - startTime,
        filteredCount,
        cached: false,
        seed
      }
    };
    if (filteredItems.length > 0) {
      setToCache(cacheKey, result);
    }
    return jsonResponse(result);
  } catch (err) {
    console.error("[Function] \u5904\u7406\u8BF7\u6C42\u5931\u8D25:", err);
    let errorMsg = "\u751F\u6210\u5931\u8D25\uFF0C\u8BF7\u7A0D\u540E\u518D\u8BD5";
    let errorCode = "UNKNOWN_ERROR";
    if (err.message.includes("API_KEY") || err.message.includes("\u672A\u914D\u7F6E")) {
      errorMsg = "LLM \u670D\u52A1\u914D\u7F6E\u9519\u8BEF\uFF0C\u8BF7\u8054\u7CFB\u7BA1\u7406\u5458";
      errorCode = "LLM_CONFIG_ERROR";
    } else if (err.message.includes("429")) {
      errorMsg = "LLM \u670D\u52A1\u8BF7\u6C42\u9891\u7387\u8D85\u9650\uFF0C\u8BF7\u7A0D\u540E\u518D\u8BD5";
      errorCode = "LLM_RATE_LIMIT";
    } else if (err.message.includes("401") || err.message.includes("403")) {
      errorMsg = "LLM \u670D\u52A1\u8BA4\u8BC1\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5 API \u5BC6\u94A5";
      errorCode = "LLM_AUTH_ERROR";
    } else if (err.message.includes("\u89E3\u6790\u5931\u8D25") || err.message.includes("\u89E3\u6790\u54CD\u5E94\u5931\u8D25")) {
      errorMsg = "LLM \u54CD\u5E94\u683C\u5F0F\u5F02\u5E38\uFF0C\u8BF7\u91CD\u8BD5";
      errorCode = "LLM_PARSE_ERROR";
    } else if (err.message.includes("500") || err.message.includes("502") || err.message.includes("503")) {
      errorMsg = "LLM \u670D\u52A1\u6682\u65F6\u4E0D\u53EF\u7528\uFF0C\u8BF7\u7A0D\u540E\u518D\u8BD5";
      errorCode = "LLM_SERVICE_ERROR";
    }
    return jsonResponse({
      error: errorMsg,
      code: errorCode,
      details: err.message
      // 保留详细信息用于调试
    }, 500);
  }
}
export {
  onRequest
};
